//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.CryptoGen.Client.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.CryptoGen.Client.Languages.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API used:.
        /// </summary>
        public static string Api_used {
            get {
                return ResourceManager.GetString("Api used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulating Supply.
        /// </summary>
        public static string CirculatingSupply {
            get {
                return ResourceManager.GetString("CirculatingSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptocurrencies.
        /// </summary>
        public static string Cryptocurrencies {
            get {
                return ResourceManager.GetString("Cryptocurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanges.
        /// </summary>
        public static string Exchanges {
            get {
                return ResourceManager.GetString("Exchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap.
        /// </summary>
        public static string MarketCap {
            get {
                return ResourceManager.GetString("MarketCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price(USD).
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data will be updated via.
        /// </summary>
        public static string TimerUpdate {
            get {
                return ResourceManager.GetString("TimerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 Cryptocurrencies.
        /// </summary>
        public static string Top10 {
            get {
                return ResourceManager.GetString("Top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume(24h).
        /// </summary>
        public static string Volume_24h_ {
            get {
                return ResourceManager.GetString("Volume(24h)", resourceCulture);
            }
        }
    }
}
